// Checks support.html — the page Apple's Support URL points at.
//
// SCOPE, AND WHY IT IS THIS NARROW. The policy page next door is NOT checked
// here. It is generated by scripts/build-legal-page.mjs in the max-ai repo and
// checked against the live site by scripts/verify-legal-page.mjs on a daily
// schedule (.github/workflows/legal-page.yml). This file was originally
// written to check both, by an agent that had not found those — which made it
// a second generator and a second verifier for a page that already had one.
// That is the same two-copies-of-one-document failure the policy page itself
// suffered, rebuilt one directory over. The policy half is deleted; only the
// support page, which has no owner elsewhere, is checked here.
//
// The delete instructions are compared against the labels the app actually
// renders, read out of its i18n strings. Renaming a button in the app fails
// this check rather than leaving the support page telling people to tap
// something that is not there.
//
// Usage:
//   node verify-support.mjs /path/to/max-ai/src/terms-content.js

import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const termsPath = process.argv[2]
if (!termsPath) {
  console.error('usage: node verify-support.mjs /path/to/max-ai/src/terms-content.js')
  process.exit(1)
}

const src = await import(pathToFileURL(resolve(termsPath)).href)

let failed = 0
const t = (label, ok, extra = '') => {
  console.log((ok ? '  ok   ' : ' FAIL  ') + label + (extra ? '   ' + extra : ''))
  if (!ok) failed++
}

// Markup out, entities back, whitespace flattened. Both sides of every text
// comparison below go through this, including the source, so a list item
// rendered as <li> compares equal to a "- " line.
const flat = (s) =>
  String(s)
    // Style and script CONTENTS are text too, and stripping only their tags
    // left ~3.9k of CSS and JS in the "visible" string. That silently broke
    // the no-extra-text check below, which is the one check whose whole job
    // is noticing content that is not in the policy.
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/^[-\s]+|\n\s*-\s*/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()

// ── THE SUPPORT PAGE ──────────────────────────────────────────────────────
// Apple's Support URL points here, so a reviewer who cannot sign in lands on
// it. Everything it must carry is asserted, and the delete instructions are
// compared against the labels the app actually renders — read from the app's
// strings module, not typed from memory. If a button is renamed in the app,
// this fails rather than leaving the support page telling people to tap
// something that is not there.
console.log('— support page —')
const support = readFileSync(resolve(here, 'support.html'), 'utf8')
const supportText = flat(support)
t('support.html exists and is a page', support.length > 6000, `${support.length} bytes`)
t('support text is substantial', supportText.length > 2000, `${supportText.length} chars`)

const strings = await import(pathToFileURL(resolve(dirname(resolve(termsPath)), 'i18n/strings.js')).href)
const ST = strings.STRINGS || strings.default
t("the app's strings module was read", Boolean(ST?.settings?.en?.dangerZone), ST?.settings?.en?.dangerZone || 'MISSING')

for (const lang of ['en', 'ar']) {
  const st = ST.settings[lang]
  for (const key of ['dangerZone', 'deleteAccount', 'deleteWord', 'deleteForever', 'title']) {
    const label = st[key]
    if (!label) { t(`app string exists: settings.${lang}.${key}`, false, 'cannot check a label the app does not define'); continue }
    t(`support page names the ${lang} "${label}"`, supportText.includes(label))
  }
}

t('contact email present', supportText.includes('maxcapitalkw@gmail.com'))
t('mailto link present', support.includes('mailto:maxcapitalkw@gmail.com'))
t('links to the policy', /href="index\.html"/.test(support))
t('links to the deletion page', /href="delete\.html"/.test(support))
t('links to the in-app terms', support.includes('https://maxaikw.com/terms'))
t('links to the services page', support.includes('https://maxaikw.com/services'))
t('both language panes present', /id="doc-en"/.test(support) && /id="doc-ar"/.test(support))
t('Arabic pane starts hidden, English does not', /id="doc-ar"[^>]*hidden/.test(support) && !/id="doc-en"[^>]*hidden/.test(support))
t('says what Aalim is', /What Aalim is/.test(support) && support.includes('شنو هو عالِم'))
t('says it can be wrong', /it can be wrong/.test(support) && support.includes('يمكن يغلط'))
t('no login is required to read it', !/login|sign in to|authenticate/i.test(supportText.replace(/cannot sign in|تسجّل دخول/g, '')))

// One stylesheet, two pages. Drift here is a visual break nobody would catch.
const styleOf = (html) => html.slice(html.indexOf('<style>'), html.indexOf('</style>'))
const policy = readFileSync(resolve(here, 'index.html'), 'utf8')
t('support and policy share one stylesheet', styleOf(support) === styleOf(policy), styleOf(support) === styleOf(policy) ? `${styleOf(support).length} chars, identical` : 'the two blocks differ')

// Every relative link must resolve to a file that exists in this repo — the
// support page is the one page a reviewer reaches when nothing else works.
for (const rel of new Set([...support.matchAll(/href="(?!https?:|mailto:|#)([^"]+)"/g)].map((x) => x[1]))) {
  let ok = true
  try { readFileSync(resolve(here, rel)) } catch { ok = false }
  t(`relative link resolves: ${rel}`, ok)
}

console.log(failed === 0 ? '\nALL CHECKS PASSED' : `\n${failed} CHECK(S) FAILED`)
process.exit(failed === 0 ? 0 : 1)
